// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/omecodes/omestore/ent/access"
	"github.com/omecodes/omestore/ent/predicate"
	"github.com/omecodes/omestore/ent/user"
)

// AccessUpdate is the builder for updating Access entities.
type AccessUpdate struct {
	config
	hooks      []Hook
	mutation   *AccessMutation
	predicates []predicate.Access
}

// Where adds a new predicate for the builder.
func (au *AccessUpdate) Where(ps ...predicate.Access) *AccessUpdate {
	au.predicates = append(au.predicates, ps...)
	return au
}

// SetCreator sets the creator field.
func (au *AccessUpdate) SetCreator(s string) *AccessUpdate {
	au.mutation.SetCreator(s)
	return au
}

// SetCreatedAt sets the created_at field.
func (au *AccessUpdate) SetCreatedAt(i int64) *AccessUpdate {
	au.mutation.ResetCreatedAt()
	au.mutation.SetCreatedAt(i)
	return au
}

// AddCreatedAt adds i to created_at.
func (au *AccessUpdate) AddCreatedAt(i int64) *AccessUpdate {
	au.mutation.AddCreatedAt(i)
	return au
}

// SetOwnerID sets the owner edge to User by id.
func (au *AccessUpdate) SetOwnerID(id string) *AccessUpdate {
	au.mutation.SetOwnerID(id)
	return au
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (au *AccessUpdate) SetNillableOwnerID(id *string) *AccessUpdate {
	if id != nil {
		au = au.SetOwnerID(*id)
	}
	return au
}

// SetOwner sets the owner edge to User.
func (au *AccessUpdate) SetOwner(u *User) *AccessUpdate {
	return au.SetOwnerID(u.ID)
}

// Mutation returns the AccessMutation object of the builder.
func (au *AccessUpdate) Mutation() *AccessMutation {
	return au.mutation
}

// ClearOwner clears the owner edge to User.
func (au *AccessUpdate) ClearOwner() *AccessUpdate {
	au.mutation.ClearOwner()
	return au
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (au *AccessUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := au.mutation.Creator(); ok {
		if err := access.CreatorValidator(v); err != nil {
			return 0, &ValidationError{Name: "creator", err: fmt.Errorf("ent: validator failed for field \"creator\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(au.hooks) == 0 {
		affected, err = au.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			au.mutation = mutation
			affected, err = au.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(au.hooks) - 1; i >= 0; i-- {
			mut = au.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, au.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccessUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccessUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccessUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

func (au *AccessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   access.Table,
			Columns: access.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: access.FieldID,
			},
		},
	}
	if ps := au.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: access.FieldCreator,
		})
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: access.FieldCreatedAt,
		})
	}
	if value, ok := au.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: access.FieldCreatedAt,
		})
	}
	if au.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   access.OwnerTable,
			Columns: []string{access.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   access.OwnerTable,
			Columns: []string{access.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// AccessUpdateOne is the builder for updating a single Access entity.
type AccessUpdateOne struct {
	config
	hooks    []Hook
	mutation *AccessMutation
}

// SetCreator sets the creator field.
func (auo *AccessUpdateOne) SetCreator(s string) *AccessUpdateOne {
	auo.mutation.SetCreator(s)
	return auo
}

// SetCreatedAt sets the created_at field.
func (auo *AccessUpdateOne) SetCreatedAt(i int64) *AccessUpdateOne {
	auo.mutation.ResetCreatedAt()
	auo.mutation.SetCreatedAt(i)
	return auo
}

// AddCreatedAt adds i to created_at.
func (auo *AccessUpdateOne) AddCreatedAt(i int64) *AccessUpdateOne {
	auo.mutation.AddCreatedAt(i)
	return auo
}

// SetOwnerID sets the owner edge to User by id.
func (auo *AccessUpdateOne) SetOwnerID(id string) *AccessUpdateOne {
	auo.mutation.SetOwnerID(id)
	return auo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (auo *AccessUpdateOne) SetNillableOwnerID(id *string) *AccessUpdateOne {
	if id != nil {
		auo = auo.SetOwnerID(*id)
	}
	return auo
}

// SetOwner sets the owner edge to User.
func (auo *AccessUpdateOne) SetOwner(u *User) *AccessUpdateOne {
	return auo.SetOwnerID(u.ID)
}

// Mutation returns the AccessMutation object of the builder.
func (auo *AccessUpdateOne) Mutation() *AccessMutation {
	return auo.mutation
}

// ClearOwner clears the owner edge to User.
func (auo *AccessUpdateOne) ClearOwner() *AccessUpdateOne {
	auo.mutation.ClearOwner()
	return auo
}

// Save executes the query and returns the updated entity.
func (auo *AccessUpdateOne) Save(ctx context.Context) (*Access, error) {
	if v, ok := auo.mutation.Creator(); ok {
		if err := access.CreatorValidator(v); err != nil {
			return nil, &ValidationError{Name: "creator", err: fmt.Errorf("ent: validator failed for field \"creator\": %w", err)}
		}
	}

	var (
		err  error
		node *Access
	)
	if len(auo.hooks) == 0 {
		node, err = auo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AccessMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			auo.mutation = mutation
			node, err = auo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(auo.hooks) - 1; i >= 0; i-- {
			mut = auo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, auo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccessUpdateOne) SaveX(ctx context.Context) *Access {
	a, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return a
}

// Exec executes the query on the entity.
func (auo *AccessUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccessUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (auo *AccessUpdateOne) sqlSave(ctx context.Context) (a *Access, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   access.Table,
			Columns: access.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: access.FieldID,
			},
		},
	}
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Access.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := auo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: access.FieldCreator,
		})
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: access.FieldCreatedAt,
		})
	}
	if value, ok := auo.mutation.AddedCreatedAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: access.FieldCreatedAt,
		})
	}
	if auo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   access.OwnerTable,
			Columns: []string{access.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   access.OwnerTable,
			Columns: []string{access.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	a = &Access{config: auo.config}
	_spec.Assign = a.assignValues
	_spec.ScanValues = a.scanValues()
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{access.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return a, nil
}
