// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Access is the predicate function for access builders.
type Access func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
